import { createSlice } from '@reduxjs/toolkit';

const mockTickets = [
  {
    ticketNumber: 'TCK-1001',
    subject: 'Salary advance request not submitted',
    customer: 'Rahul Sharma',
    platform: 'Mobile App',
    priority: 'High',
    status: 'Open',
    assignedTo: 'Anita Verma',
    slaRemaining: '02h 10m',
    createdAt: '2026-03-08 10:12',
    slaBreached: false,
    resolvedToday: false,
    closedToday: false,
  },
  {
    ticketNumber: 'TCK-1002',
    subject: 'Unable to upload bank statement',
    customer: 'Priya Singh',
    platform: 'Web Portal',
    priority: 'Medium',
    status: 'In Progress',
    assignedTo: 'Rohit Nair',
    slaRemaining: '01h 05m',
    createdAt: '2026-03-08 11:45',
    slaBreached: false,
    resolvedToday: false,
    closedToday: false,
  },
  {
    ticketNumber: 'TCK-1003',
    subject: 'KYC verification delayed',
    customer: 'Amit Yadav',
    platform: 'Mobile App',
    priority: 'High',
    status: 'Escalated',
    assignedTo: 'Sana Khan',
    slaRemaining: '00h 00m',
    createdAt: '2026-03-07 16:30',
    slaBreached: true,
    resolvedToday: false,
    closedToday: false,
  },
  {
    ticketNumber: 'TCK-1004',
    subject: 'Disbursal date clarification needed',
    customer: 'Nitin Kapoor',
    platform: 'Call Center',
    priority: 'Low',
    status: 'Closed',
    assignedTo: 'Anita Verma',
    slaRemaining: 'Closed',
    createdAt: '2026-03-06 09:40',
    slaBreached: false,
    resolvedToday: true,
    closedToday: true,
  },
  {
    ticketNumber: 'TCK-1005',
    subject: 'EMI schedule mismatch',
    customer: 'Meera Joshi',
    platform: 'Web Portal',
    priority: 'Medium',
    status: 'In Progress',
    assignedTo: 'Vikas Rao',
    slaRemaining: '03h 45m',
    createdAt: '2026-03-05 14:18',
    slaBreached: false,
    resolvedToday: false,
    closedToday: false,
  },
  {
    ticketNumber: 'TCK-1006',
    subject: 'Need help with profile update',
    customer: 'Karan Bhatia',
    platform: 'Mobile App',
    priority: 'Low',
    status: 'Open',
    assignedTo: 'Rohit Nair',
    slaRemaining: '05h 20m',
    createdAt: '2026-03-05 18:05',
    slaBreached: false,
    resolvedToday: false,
    closedToday: false,
  },
  {
    ticketNumber: 'TCK-1007',
    subject: 'Loan status not updating',
    customer: 'Neha Arora',
    platform: 'Web Portal',
    priority: 'High',
    status: 'Escalated',
    assignedTo: 'Sana Khan',
    slaRemaining: '00h 00m',
    createdAt: '2026-03-04 13:22',
    slaBreached: true,
    resolvedToday: false,
    closedToday: false,
  },
  {
    ticketNumber: 'TCK-1008',
    subject: 'Document rejected without reason',
    customer: 'Suresh Patel',
    platform: 'Mobile App',
    priority: 'Medium',
    status: 'In Progress',
    assignedTo: 'Vikas Rao',
    slaRemaining: '00h 35m',
    createdAt: '2026-03-03 15:09',
    slaBreached: false,
    resolvedToday: false,
    closedToday: false,
  },
  {
    ticketNumber: 'TCK-1009',
    subject: 'Interest rate query',
    customer: 'Divya Menon',
    platform: 'Call Center',
    priority: 'Low',
    status: 'Closed',
    assignedTo: 'Anita Verma',
    slaRemaining: 'Closed',
    createdAt: '2026-03-02 12:48',
    slaBreached: false,
    resolvedToday: true,
    closedToday: true,
  },
  {
    ticketNumber: 'TCK-1010',
    subject: 'Cannot download sanction letter',
    customer: 'Arjun Malhotra',
    platform: 'Web Portal',
    priority: 'Medium',
    status: 'Open',
    assignedTo: 'Rohit Nair',
    slaRemaining: '06h 15m',
    createdAt: '2026-03-01 09:14',
    slaBreached: false,
    resolvedToday: false,
    closedToday: false,
  },
];

const initialState = {
  loading: false,
  error: null,
  rows: mockTickets,
  page: 1,
  rowsPerPage: 5,
};

const customerManagementSlice = createSlice({
  name: 'customerManagement',
  initialState,
  reducers: {
    setCustomerManagementPage: (state, action) => {
      state.page = action.payload;
    },
    setCustomerManagementRowsPerPage: (state, action) => {
      state.rowsPerPage = action.payload;
      state.page = 1;
    },
  },
});

export const {
  setCustomerManagementPage,
  setCustomerManagementRowsPerPage,
} = customerManagementSlice.actions;

export default customerManagementSlice.reducer;
